services:
  api:
    image: ubrato-back-api
    container_name: ubrato-back-api
    hostname: backend
    restart: unless-stopped
    expose:
      - "8000"
    networks:
      - ubrato-back-network
      - ubrato-back-postgres-network
      - ubrato-back-redis-network
      - ubrato-back-typesense-network
      - ubrato-back-nats-network
    env_file:
      - .env

  postgres_migration:
    image: ubrato-back-api
    container_name: ubrato-back-postgres-migration
    command: alembic upgrade head
    restart: on-failure
    networks:
      - ubrato-back-postgres-network
    env_file:
      - .env

  typesense_migration:
    image: ubrato-back-typesense-migration
    container_name: ubrato-back-typesense-migration
    restart: on-failure
    networks:
      - ubrato-back-typesense-network
    env_file:
      - .env

  postgres:
    image: postgres:17-alpine
    container_name: ubrato-back-postgres
    hostname: back-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - ubrato-back-postgres-network
    volumes:
      - ubrato-back-postgres-data:/var/lib/postgresql/users:rw
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DATABASE} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8.0-alpine
    container_name: ubrato-back-redis
    hostname: back-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: unless-stopped
#    ports:
#      - "6379:6379"
    networks:
      - ubrato-back-redis-network
    volumes:
      - ubrato-back-redis-data:/data

  typesense:
    image: typesense/typesense:28.0-amd64
    container_name: ubrato-back-typesense
    hostname: ubrato-back-typesense
    command: --data-dir /data --api-key=${TYPESENSE_API_KEY} --enable-cors
    restart: unless-stopped
    # ports:
    #   - "8108:8108"
    networks:
      - ubrato-back-typesense-network
    volumes:
      - ubrato-back-typesense-data:/data

  typesense-web:
    image: ghcr.io/bfritscher/typesense-dashboard:latest
    container_name: ubrato-back-typesense-web
    hostname: back-typesense-web
    restart: unless-stopped
    # ports:
    #   - "3003:80"
    networks:
      - ubrato-back-typesense-network
    volumes:
      - ./typesense-config.json:/srv/config.json

  nats:
    image: nats:2.11.4-alpine3.21
    container_name: ubrato-back-nats
    hostname: back-nats
    command:
      - "--name=ubrato-back-nats"
      - "--http_port=8222"
      - "--js"
      - "--sd=/data"
    restart: unless-stopped
    # ports:
    #   - "4222:4222"  # NATS client port
    #   - "6222:6222"  # NATS cluster port
    #   - "8222:8222"  # NATS monitoring port
    networks:
      - ubrato-back-nats-network
    volumes:
      - ubrato-back-nats-data:/data

volumes:
  ubrato-back-postgres-data:
    name: ubrato-back-postgres-data
  ubrato-back-redis-data:
    name: ubrato-back-redis-data
  ubrato-back-typesense-data:
    name: ubrato-back-typesense-data
  ubrato-back-nats-data:
    name: ubrato-back-nats-data

networks:
  ubrato-back-network:
    name: ubrato-back-network
  ubrato-back-postgres-network:
    name: ubrato-back-postgres-network
  ubrato-back-redis-network:
    name: ubrato-back-redis-network
  ubrato-back-typesense-network:
    name: ubrato-back-typesense-network
  ubrato-back-nats-network:
    name: ubrato-back-nats-network
