services:
  front:
    image: registry.ubrato.ru/ubrato-front:latest
    container_name: ubrato-front
    hostname: front
    restart: unless-stopped
    networks:
      - ubrato-front-network
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"

networks:
  ubrato-front-network:
    name: ubrato-front-network
